"""
Alert model - Alerts generated by diagnostic engine.
"""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, DateTime, ForeignKey, Index, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base

if TYPE_CHECKING:
    from app.models.workspace import Workspace


class Alert(Base):
    """Alerts generated by diagnostic engine."""

    __tablename__ = "alerts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("workspaces.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    integration_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("integrations.id", ondelete="SET NULL"),
        nullable=True,
    )
    execution_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("executions.id", ondelete="SET NULL"),
        nullable=True,
    )
    monitor_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("monitors.id", ondelete="SET NULL"),
        nullable=True,
    )
    credential_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("credentials.id", ondelete="SET NULL"),
        nullable=True,
    )
    severity: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
    )  # info | warning | critical
    category: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
    )  # auth | api | logic | schema | infra | ai | silent
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    root_cause: Mapped[str | None] = mapped_column(Text, nullable=True)
    suggested_fix: Mapped[str | None] = mapped_column(Text, nullable=True)
    auto_remediated: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
    )
    remediation_log: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    # Incident identity. One row per ongoing incident, not one per detection:
    # a monitor that stays down is a single alert whose occurrence_count and
    # last_seen_at advance, rather than a new row on every check.
    dedup_key: Mapped[str | None] = mapped_column(String(255), nullable=True)
    occurrence_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1, server_default="1"
    )
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    acknowledged_by: Mapped[str | None] = mapped_column(String(255), nullable=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    # Relationships
    workspace: Mapped["Workspace"] = relationship(
        "Workspace",
        back_populates="alerts",
        lazy="raise",
    )

    # Indexes
    __table_args__ = (
        Index(
            "idx_alerts_workspace_created", "workspace_id", "created_at", postgresql_using="btree"
        ),
        Index(
            "idx_alerts_unresolved",
            "workspace_id",
            "severity",
            postgresql_where=resolved_at.is_(None),
        ),
        # At most one OPEN incident per (workspace, dedup_key). The predicate is
        # what makes an incident re-openable: once resolved_at is set the row
        # leaves the index, so a recurrence creates a genuinely new incident
        # rather than resurrecting the closed one.
        Index(
            "uq_alerts_open_incident",
            "workspace_id",
            "dedup_key",
            unique=True,
            postgresql_where=resolved_at.is_(None),
        ),
    )

    def __repr__(self) -> str:
        return f"<Alert(id={self.id}, severity={self.severity}, category={self.category}, title={self.title})>"
